version: "3.9"
services:
  backend:
    build: .
    command: bash -c "sleep 10 && rails db:migrate && echo 'migrating ---' && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/BackAppNotes
    ports:
      - "3000:3000"
